export const movieList = [
  "The Matrix",
  "Inception",
  "Interstellar",
  "The Prestige",
  "Memento",
  "The Dark Knight",
  "Titanic",
  "Avatar",
  "The Lion King",
  "Jurassic Park",
  "Pulp Fiction",
  "Forrest Gump",
  "The Lord of the Rings",
  "Star Wars",
  "Gladiator",
  "Fight Club",
  "The Godfather",
  "The Shawshank Redemption",
  "Schindler's List",
  "The Godfather Part II",
  "The Silence of the Lambs",
  "Saving Private Ryan",
  "Coco",
  "Up",
  "La La Land",
  "Braveheart",
  "The Green Mile",
  "Se7en",
  "The Departed",
  "The Last Samurai",
  "Django Unchained",
  "The Great Gatsby",
  "The Wolf of Wall Street",
  "Shutter Island",
  "Gone Girl",
  "Whiplash",
  "Mad Max: Fury Road",
  "Gravity",
  "Interstellar",
  "Guardians of the Galaxy",
  "Avengers: Endgame",
  "The Avengers",
  "Avengers: Infinity War",
  "Black Panther",
  "Iron Man",
  "Thor: Ragnarok",
  "Spider-Man: Into the Spider-Verse",
  "Logan",
  "Deadpool",
  "Wonder Woman",
  "The Incredibles",
  "Finding Nemo",
  "Toy Story",
  "Toy Story 3",
  "Toy Story 4",
  "Ratatouille",
  "Monsters, Inc.",
  "Cars",
  "The Good Dinosaur",
  "Onward",
  "Frozen",
  "Moana",
  "Zootopia",
  "The Lion King (2019)",
  "Aladdin",
  "Beauty and the Beast",
  "The Little Mermaid",
  "Cinderella",
  "Pirates of the Caribbean: The Curse of the Black Pearl",
  "Harry Potter and the Sorcerer's Stone",
  "Harry Potter and the Deathly Hallows: Part 2",
  "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
  "The Hobbit: An Unexpected Journey",
  "The Hunger Games",
  "Divergent",
  "The Maze Runner",
  "Twilight",
  "The Notebook",
  "A Walk to Remember",
  "La La Land",
  "Eternal Sunshine of the Spotless Mind",
  "The Truman Show",
  "Catch Me If You Can",
  "The Great Escape",
  "Amélie",
  "City of God",
  "Pan's Labyrinth",
  "The Lives of Others",
  "The Secret in Their Eyes",
  "A Beautiful Mind",
  "Her",
  "Ex Machina",
  "Inglourious Basterds",
  "Blade Runner 2049",
  "District 9",
];
